### PR TITLE
feat: index based order tracking

### PR DESCRIPTION
**Pull request by jaketimothy**
Note: This is a breaking change for contract storage map

### CODE REVIEW

**Review by joshualyguessennd — APPROVED** [review]

**Comment by joshualyguessennd** [comment]
is it possible to wait and merge it last ?

**Comment by jaketimothy** [comment]
@joshualyguessennd Are you ok with this coming in now?

**Comment by joshualyguessennd** [comment]
Yes, let's do it

**Comment by jaketimothy** [comment]
Fixes https://github.com/sherlock-audit/2023-06-dinari-judging/issues/106

**Pull request merged**
