### PR TITLE
feat: token stock split

### PR DESCRIPTION
**Pull request by jaketimothy**
This introduces a token factory that handles initial deployments and splits. Minimal changes are made to to the token to lock down minting and burning after a call to `split`. `split` deploys a new token. Holders of the legacy token can call `convert` on token factory to burn legacy token for new token according to the (aggregate) split multiple.

### CODE REVIEW

**Comment by jaketimothy** [comment]
Alternative to #128

**Comment by joshualyguessennd** [comment]
I like this approach

**Comment by ykim** [comment]
I prefer this approach over the other also. It allows us a clean way of migrating tokens in the future. For example, we can retain our current implementation of `BridgedERC20Token`, convert this version to `BridgedERC20TokenV2`, and have the contract "split" (aka migrate) from `BridgedERC20Token` to `BridgedERC20TokenV2`.

**Comment by jaketimothy** [comment]
@ykim This PR addresses the audit concern around stock splits. I'll create a migration tool in a separate PR before we deploy anything new.

**Review by ykim — APPROVED** [review]

**Review by joshualyguessennd — APPROVED** [review]

**Comment by jaketimothy** [comment]
Fixes https://github.com/sherlock-audit/2023-06-dinari-judging/issues/29

**Pull request merged**
